[Db]
	addr = "127.0.0.1:5232"
	dsn = "live_form:CHl1PL0@tcp(127.0.0.1:5232)/live_form?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "50s"
	execTimeout = "50s"
	tranTimeout = "50s"