[Db]
    dsn = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8&parseTime=True&loc=Local"

[Email]
	emailUser = "18683565829@163.com"
    emailPwd  = "HDfw5LRPKFKevU6E"
    emailHost = "smtp.163.com"
    emailPort = 25


[Moonshot]
	url = "https://api.moonshot.cn/v1/chat/completions"
    authorization  = "Bearer sk-D3lXzQcv8Uflx0AjdyolQdjGlO7yPa7be0oligkSt2dfX7Ab"
