[Db]
	dsn = "jiang:D77jB5bTNSyKF7jb@tcp(127.0.0.1:3306)/jiang?charset=utf8&parseTime=True&loc=Local"

[Email]
	emailUser = "18683565829@163.com"
    emailPwd  = "HDfw5LRPKFKevU6E"
    emailHost = "smtp.163.com"
    emailPort = 25